name: Ruby

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0']

    steps:
    - uses: actions/checkout@v2
    - name: Set Up ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v1
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    # TODO: use cache
    - name: Download Font
      run: curl "https://fonts.google.com/download?family=Noto%20Sans%20JP" -o fonts.zip
    - name: Unzip Fonts
      run: unzip fonts.zip -d ./fonts
    - name: Create Movie Test
      run: ffmpeg -r 30 -loop 1 -t 2 -i chara/aisatsu-2.png -vcodec libx264 -pix_fmt yuv420p -y movies/movie.mp4
    - uses: actions/upload-artifact@v2
      with:
        name: movies
        path: movies/
